FROM denoland/deno:alpine

EXPOSE 8080
WORKDIR /app

ARG GITHUB
ARG WEBHOOK
ARG CAPTCHA_PUBLIC
ARG CAPTCHA_PRIVATE

ENV PORT=8080
ENV GITHUB=${GITHUB}
ENV WEBHOOK=${WEBHOOK}
ENV CAPTCHA_PUBLIC=${CAPTCHA_PUBLIC}
ENV CAPTCHA_PRIVATE=${CAPTCHA_PRIVATE}

COPY . /app

RUN deno cache mod.ts

CMD ["deno", "task", "run"]
