FROM denoland/deno:alpine

EXPOSE 8080
WORKDIR /app

ARG GITHUB
ARG WEBHOOK
ARG TURNSTILE_PUBLIC
ARG TURNSTILE_PRIVATE

ENV PORT=8080 GITHUB=${GITHUB} WEBHOOK=${WEBHOOK} TURNSTILE_PUBLIC=${TURNSTILE_PUBLIC} TURNSTILE_PRIVATE=${TURNSTILE_PRIVATE}

COPY . /app

RUN deno cache mod.ts

CMD ["deno", "task", "run"]
